name: Create StoryBook Page
on:
  push:
    branches-ignore: ["gh-pages"]
jobs:
  Create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.OS }}-build-${{ env.cache-name }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Build storybook
        run: yarn build-storybook
      - name: Git init # cloneせずに、最小限のファイルのみを管理対象とする
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |          
          BRANCH=`echo $GITHUB_REF | sed 's/^refs\/heads\///' | sed -e 's/\//-/g'`
          mkdir -p __gh-pages__/stories
          cd __gh-pages__
          git init
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email ${GITHUB_ACTOR}@git
          git config core.sparsecheckout true
          git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          echo /stories/${BRANCH} > .git/info/sparse-checkout
          echo /stories/index.txt >> .git/info/sparse-checkout
          echo /index.html >> .git/info/sparse-checkout
          git pull origin gh-pages || true
          git checkout -b gh-pages
      - name: Create gh-pages
        run: |
          BRANCH=`echo $GITHUB_REF | sed 's/^refs\/heads\///' | sed -e 's/\//-/g'`
          cd __gh-pages__
          rm -rf stories/${BRANCH} || true
          mv ../storybook-static stories/${BRANCH}
          cp -f ../.github/workflows/res/index.html .
          cd stories
          echo -e "`git ls-files | sed -r 's/^stories\/([^\/]+)\/.*/\1/;t;d'`\n${BRANCH}" | uniq > stories/index.txt
      - name: Save gh-pages
        run: |
          BRANCH=`echo $GITHUB_REF | sed 's/^refs\/heads\///'`
          cd __gh-pages__
          git add .
          git commit -m "$BRANCH" || true
          git push origin gh-pages || true
