name: Delete StoryBook Page 
on:
  delete:
jobs:
  Delete:
    runs-on: ubuntu-latest
    steps:
      - name: Git init # cloneせずに、最小限のファイルのみを管理対象とする
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |          
          BRANCH=`echo ${{github.event.ref}} | sed -e 's/\//-/g'`
          mkdir -p __gh-pages__/stories
          cd __gh-pages__
          git init
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email ${GITHUB_ACTOR}@git
          git config core.sparsecheckout true
          git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          echo /stories/${BRANCH} > .git/info/sparse-checkout
          echo /stories/index.txt >> .git/info/sparse-checkout
          git pull origin gh-pages || true
          git checkout -b gh-pages
      - name: Delete gh-pages
        run: |
          BRANCH=`echo ${{github.event.ref}} | sed -e 's/\//-/g'`
          cd __gh-pages__
          rm -rf stories/${BRANCH} || exit 0
          echo -e "`git ls-files | sed -r 's/^stories\/([^\/]+)\/.*/\1/;t;d'`" | uniq | grep -v ${BRANCH} > stories/index.txt
      - name: Save gh-pages
        run: |
          cd __gh-pages__
          git add .
          git commit -m "${{github.event.ref}}" || true
          git push origin gh-pages || true
